services:
  taxi-redis:
    image: redislabs/redismod
    container_name: taxi-redis
    ports:
      - "6379:6379"
    networks:
      - taxinet

  taxi-postgres:
    image: postgres
    container_name: taxi-database
    ports:
      - "5432:5432"
    shm_size: 128mb
    environment:
      POSTGRES_DB: taxi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - taxi_db:/var/lib/postgresql/data
      - "./server/db:/docker-entrypoint-init.d"
    networks:
      - taxinet

  taxi-server:
    build:
      context: ./server
    command: python manage.py runserver 0.0.0.0:8000
    container_name: taxi-server
    depends_on:
      - taxi-postgres
      - taxi-redis
    environment:
      - REDIS_URL=redis://taxi-redis:6379/0
      - PGDATABASE=taxi
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=taxi-database
    ports:
      - "8001:8000"
    networks:
      - taxinet

  taxi-client:
    build:
      context: ./client
    command: ng serve --host 0.0.0.0
    container_name: taxi-client
    depends_on:
      - taxi-server
    environment:
      - CHROME_BIN=/usr/bin/chromium
    ports:
      - "4201:4200"
    networks:
      - taxinet

volumes:
  taxi_db:

networks:
  taxinet:
    driver: bridge
